# Generated by Django 5.0.7 on 2024-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathermodel',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Иконка погоды'),
        ),
        migrations.AddField(
            model_name='weathermodel',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура'),
        ),
    ]
